name: Test and Deploy
on: push

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    name: Yocoin Testing
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        otp: [24.0.3]
        elixir: [1.12.1]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install Elixir Deps
        run: |
          mix deps.get
      - run: mix test

  deploy:
    needs: test
    name: Yocoin Deployment
    if: github.ref == 'refs/heads/trunk'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"
